npm_build:
  image: node:latest
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - out
    expire_in: 1 week

pages:
  image: alpine:latest
  stage: deploy
  only:
    - master
  when: on_success
  script:
    - mv ./public ./public.nextjs
    - mv ./out ./public
  artifacts:
    paths:
      - public
    expire_in: 1 week
