npm_build:
  image: node:lts
  stage: build
  before_script:
    - npm ci
  script:
    - export PUBLIC_CANONICAL_URL="https://kobo-offline.virgulilla.com"
    - export PUBLIC_GITLAB_PAGES_URL="https://roboe.gitlab.io/kobo-offline"
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 week

pages:
  image: alpine:latest
  stage: deploy
  only:
    - master
  when: on_success
  script:
    - mv ./public ./public.source
    - mv ./build ./public
  artifacts:
    paths:
      - public
    expire_in: 1 week
