import { Page } from '@nakedjsx/core/page'

import mainStyle from ':sass:../assets/styles/main.scss'
import DEVICES from ':json:../data/kobo/devices.json'
import DICTIONARIES from ':json:../data/kobo/dictionaries.json'

import Home from '../components/Home.jsx'
import processHomeProps from './index-props.js'

const PUBLIC_CANONICAL_URL =
  process.env.PUBLIC_CANONICAL_URL ?? 'http://localhost:8999'
const PUBLIC_GITLAB_PAGES_URL = process.env.PUBLIC_GITLAB_PAGES_URL ?? undefined

const homeProps = await processHomeProps(DEVICES, DICTIONARIES)

Page.Create('en')
Page.AppendHead(<meta charSet="utf-8" />)
Page.AppendHead(
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
)
Page.AppendHead(<meta name="theme-color" content="#000000" />)
Page.AppendHead(<meta name="description" content="Generated by NakedJSX" />)
Page.AppendHead(<link rel="shortcut icon" href="/favicon.ico" />)
Page.AppendHead(<link rel="canonical" href={PUBLIC_CANONICAL_URL} />)
Page.AppendHead(<title>Kobo Offline</title>)
Page.AppendCss(mainStyle)
Page.AppendJs(`
  /* @license magnet:?xt=urn:btih:90dc5c0be029de84e523b9b3922520e79e0e6f08&dn=cc0.txt */

  if (
    window.location.origin + window.location.pathname === '${PUBLIC_GITLAB_PAGES_URL}/'
    ) {
      window.location = window.location
      .toString()
      .replace('${PUBLIC_GITLAB_PAGES_URL}', '${PUBLIC_CANONICAL_URL}')
    }
`)
Page.AppendBody(<Home {...homeProps} />)
Page.Render()
